import type { NextPage } from "next";
import Head from "next/head";
import { Provider } from "react-redux";
import { ExchangeForm } from "../src/components/organisms/ExchangeForm";
import { Page } from "../src/components/templates/Page";
import store from "../src/redux/rootStore";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Cryptocurrency frontend test assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page>
        <Provider store={store}>
          <ExchangeForm />
        </Provider>
      </Page>
    </div>
  );
};

export default Home;
